### ISSUE TITLE
Short URL not compatible

### ISSUE THREAD

**Issue by dvaai** [harborsiem/YouTubeDownloader#1]
hi when i paste the short cut in the app it doesn't recognized it. Please make it work and also try and add mp3 to it thanks

**Comment by harborsiem** [comment]
Hi,
 I don't understand what you mean with the short cut. Do you have an example short cut ?
Do you have an example link for a mp3 on Youtube ? Or do you mean you want to convert a (Music) Video to a mp3 file ?

**Comment by dvaai** [comment]
try and paste this link in your app: https://youtu.be/KFq_1paJ4yc AND DOWNLOAD !!!

**Comment by harborsiem** [comment]
When you compile the latest source from the master branch, you will get the functionality you want.

**Comment by dvaai** [comment]
excuse me ???

**Comment by harborsiem** [comment]
new Version 2.3, now it works
